language: scala
scala:
    - "2.11.7"
jdk:
    - oraclejdk8

env:
    - NEO_VERSION="2.3.1"

branches:
    only:
    - master

before_install:
    - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
    - neo4j-community-$NEO_VERSION/bin/neo4j start
    - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=neo4j2"
    - curl -vX POST http://neo4j:neo4j2@localhost:7474/user/neo4j/password -d"password=neo4j"
